services:
  - type: web
    name: animebum-bot
    runtime: python
    rootDir: animebum
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: true
